
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tutut
 */
public class comprobacionNumerica extends javax.swing.JFrame {

    /**
     * Creates new form comprobacionNumerica2
     */
    public comprobacionNumerica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnComprobar = new javax.swing.JButton();
        lblEtiqueta1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 255));
        lblTitulo.setText("COMPROBACIÓN");

        btnComprobar.setText("Comprobar");
        btnComprobar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        lblEtiqueta1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblEtiqueta1.setForeground(new java.awt.Color(102, 153, 255));
        lblEtiqueta1.setText("Ingrese el Número:");

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblEtiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEtiqueta1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        // TODO add your handling code here:
        int numero = 0;
        String textoNumero = txtNumero.getText();

        if (!textoNumero.isEmpty() && textoNumero.matches("\\d+")) {
            numero = Integer.parseInt(textoNumero);

            if (numero >= 1 && numero <= 500) {
                // Verificar si es perfecto
                if (esNumeroPerfecto(numero)) {
                    JOptionPane.showMessageDialog(this, "El número " + numero + " es perfecto");
                    txtNumero.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "El número " + numero + " no es perfecto");
                    txtNumero.setText("");
                }

                if (esNumeroPrimo(numero)) {
                    JOptionPane.showMessageDialog(this, "El número " + numero + " es primo");
                    int sumatoriaPrimos = sumatoriaPrimosMenores(numero);
                    String numerosMenoresAPrimos = numerosMenoresAPrimos(numero);
                    JOptionPane.showMessageDialog(this, "Los números menores a los primos son: " + numerosMenoresAPrimos);
                    JOptionPane.showMessageDialog(this, "La sumatoria es: " + sumatoriaPrimos);
                    double raizCuadrada = Math.sqrt(sumatoriaPrimos);
                    JOptionPane.showMessageDialog(this, "La raíz cuadrada es: " + raizCuadrada);
                    txtNumero.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "El número " + numero + " no es primo");
                    txtNumero.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingresa un número entre 1 y 500");
                txtNumero.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor numérico");
        }
    }//GEN-LAST:event_btnComprobarActionPerformed
    private boolean esNumeroPerfecto(int numero) {
        if (numero <= 1) {
            return false;
        }

        int suma = 1;

        for (int i = 2; i * i <= numero; i++) {
            if (numero % i == 0) {
                suma += i;
                if (i != numero / i) {
                    suma += numero / i;
                }
            }
        }

        return suma == numero;
    }

    private boolean esNumeroPrimo(int numero) {
        if (numero <= 1) {
            return false;
        }

        for (int i = 2; i <= Math.sqrt(numero); i++) {
            if (numero % i == 0) {
                return false;
            }
        }

        return true;
    }
    private String numerosMenoresAPrimos(int numero) {
        StringBuilder numerosMenores = new StringBuilder();

        for (int i = 1; i < numero; i++) {
            if (esNumeroPrimo(i)) {
                numerosMenores.append(i).append(", ");
            }
        }
        if (numerosMenores.length() > 0) {
            numerosMenores.delete(numerosMenores.length() - 2, numerosMenores.length());
        }

        return numerosMenores.toString();
    }
    private int sumatoriaPrimosMenores(int numero) {
        int sumatoria = 0;

        for (int i = 2; i < numero; i++) {
            if (esNumeroPrimo(i)) {
                sumatoria += i;
            }
        }

        return sumatoria;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comprobacionNumerica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comprobacionNumerica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comprobacionNumerica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comprobacionNumerica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comprobacionNumerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JLabel lblEtiqueta1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
